### Create a new user
POST {{autentication}}/authentication
Content-Type: application/json

{
  "pseudo": "Xx_DarkMigShadowLeThug_xX",
  "password": "lilou2019"
}

### Connect
GET {{autentication}}/authentication
Content-Type: application/json

{
  "pseudo": "Xx_DarkMigShadowLeThug_xX",
  "password": "lilou2019"
}