### Read all products
GET {{products}}/products

### Read one product
GET {{products}}/products/1

### Read a non-existing product
GET {{products}}/products/-1

### Create one product
POST {{products}}/products
Content-Type: application/json

{
  "id": 5,
  "name": "Test",
  "category": "TestCat",
  "price": 10
}

### Create an existing product
POST {{products}}/products
Content-Type: application/json

{
  "id": 1,
  "name": "Damien",
  "category": "Muzik",
  "price": 10
}

### Update one product
PUT {{products}}/products
Content-Type: application/json

{
  "id": 3,
  "name": "Alicia",
  "category": "Contente",
  "price": 10
}

### Update a non-existing product
PUT {{products}}/products
Content-Type: application/json

{
  "id": -1,
  "name": "Emmeric",
  "category": "Annoying",
  "price": 10
}

### Delete all products
DELETE {{products}}/products

### Delete one product
DELETE {{products}}/products/5

### Delete a non-existing product
DELETE {{products}}/products/-1